name: Sync to CNB.cool
on: [push]

jobs:
  sync:
    if: github.repository == 'DragonOS-Community/test-suites'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Sync to CNB Repository
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/DragonOS-Community/test-suites.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="cnb" \
            -e PLUGIN_PASSWORD=${{ secrets.CNB_GIT_PASSWORD }} \
            -e PLUGIN_FORCE="true" \
            docker.cnb.cool/fslongjin/git-sync:250626
